name = "zen-sudoku-api"
main = "server/worker.ts"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]

[env.production]
routes = [
  { pattern = "api.zen-sudoku.com/*", zone_id = "YOUR_ZONE_ID" }
]

[[kv_namespaces]]
binding = "GAMES"
id = "331e3f4f94f44236ba51e95d23f9df6a"
preview_id = "754d2c059f6948ab9f8d16366289175d"

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "service-worker"

[env.preview]
[[env.preview.kv_namespaces]]
binding = "GAMES"
id = "754d2c059f6948ab9f8d16366289175d"
